apiVersion: apps/v1
kind: Deployment
metadata:
  name: beverage-service
  namespace: beverage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beverage-service
  template:
    metadata:
      labels:
        app: beverage-service
    spec:
      containers:
        - name: app
          image: beverage/service:1.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: beverage-config
                  key: APP_NAME
            - name: MONGO_URI
              value: "mongodb://beverage:beveragepw@mongo-db:27017/beverage?authSource=beverage"
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_DB
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
