apiVersion: v1
kind: Service
metadata:
  name: beverage-frontend
  namespace: beverage
spec:
  type: NodePort
  selector:
    app: beverage-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081
